# https://github.com/luke10x/taxx/blob/main/docker-compose.yml

version: "3.7"

services:
  app:
    image: node:12
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: "/bin/bash -c"
    command:
      - |
        CI=true yarn dev || (\
          echo '⛔ `yarn dev` failed, but the container is running...' && \
          tail -f /dev/null \
        )
    ports:
      - 3000:3000
    environment:
      API_SERVER_URL: http://api:4000/graphql
      API_CLIENT_URL: http://localhost:4000/graphql

  api:
    image: node:12
    volumes:
      - ./api:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: "/bin/bash -c"
    command:
      - |
        CI=true yarn start || (\
          echo '⛔ `yarn start` failed, but the container is running...' && \
          tail -f /dev/null \
        )
    ports:
      - 4000:4000
