# https://github.com/luke10x/taxx/blob/main/docker-compose.yml

version: "3.7"

x-variables:
  - &db_name test
  - &db_password ${MYSQL_PASSWORD}
  - &db_user ${MYSQL_USER}

services:
  app:
    image: node:12
    volumes:
      - ./app:/usr/src/app
    working_dir: /usr/src/app
    entrypoint: "/bin/bash -c"
    command:
      - |
        CI=true yarn dev || (\
          echo '⛔ `yarn dev` failed, but the container is running...' && \
          tail -f /dev/null \
        )
    ports:
      - 3000:3000
    environment:
      API_SERVER_URL: http://wordpress:4000/graphql
      API_CLIENT_URL: http://localhost:4000/graphql

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: *db_name
      MYSQL_PASSWORD: *db_password
      MYSQL_USER: *db_user
      MYSQL_RANDOM_ROOT_PASSWORD: yes
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: *db_name
      WORDPRESS_DB_USER: *db_user
      WORDPRESS_DB_PASSWORD: *db_password
    depends_on:
      - db
    ports:
      - "8080:80"
    restart: always
    volumes:
      - ./wordpress:/var/www/html

volumes:
  db_data:
